CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- tenants
--
-- `id` é BIGINT local · gerado pela nossa app (não vem do IdP). O id do
-- Zitadel fica em `zitadel_org_id` (varchar, opaco). Essa separação permite
-- trocar de IdP no futuro sem migrar FKs em cascata. Ver ADR-019.
--
-- BIGINT em vez de UUID porque: tenantId aparece em todas as tabelas como
-- FK e em todas as responses da API · economia de espaço + index reads
-- mais rápidos. UUIDs ficam para entidades de domínio (pessoas, etc.).
-- ============================================================================
CREATE TABLE tenants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zitadel_org_id  VARCHAR(255) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(100) NOT NULL UNIQUE,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_tenants_slug ON tenants(slug);
CREATE INDEX idx_tenants_zitadel_org_id ON tenants(zitadel_org_id);

CREATE TABLE users (
    id              UUID PRIMARY KEY,
    zitadel_id      VARCHAR(255) NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL,
    full_name       VARCHAR(255),
    avatar_url      TEXT,
    tenant_id       BIGINT,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL,
    last_login_at   TIMESTAMPTZ,
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL
);

CREATE INDEX idx_users_zitadel_id ON users(zitadel_id);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_tenant_id ON users(tenant_id);
